In [6]:
import pandas as pd
import os

def load_hotel_reserve():
  customer_tb = pd.read_csv('/workspaces/AIschool_data_preprocessing/notebooks/Preprocessing-excersize/data/customer.csv')
  hotel_tb = pd.read_csv('/workspaces/AIschool_data_preprocessing/notebooks/Preprocessing-excersize/data/hotel.csv')
  reserve_tb = pd.read_csv('/workspaces/AIschool_data_preprocessing/notebooks/Preprocessing-excersize/data/reserve.csv')
  return customer_tb, hotel_tb, reserve_tb


def load_holiday_mst():
  holiday_tb = pd.read_csv('/workspaces/AIschool_data_preprocessing/notebooks/Preprocessing-excersize/data/holiday_mst.csv',
                           index_col=False)
  return holiday_tb


def load_production():
  production_tb = pd.read_csv('/workspaces/AIschool_data_preprocessing/notebooks/Preprocessing-excersize/data/production.csv')
  return production_tb


def load_production_missing_num():
  production_tb = pd.read_csv('/workspaces/AIschool_data_preprocessing/notebooks/Preprocessing-excersize/data/production_missing_num.csv')
  return production_tb


def load_production_missing_category():
  production_tb = pd.read_csv('/workspaces/AIschool_data_preprocessing/notebooks/Preprocessing-excersize/data/production_missing_category.csv')
  return production_tb


def load_monthly_index():
  monthly_index_tb = \
    pd.read_csv('/workspaces/AIschool_data_preprocessing/notebooks/Preprocessing-excersize/data/monthly_index.csv')
  return monthly_index_tb


def load_meros_txt():
  with open('/workspaces/AIschool_data_preprocessing/notebooks/Preprocessing-excersize/data/txt/meros.txt', 'r') as f:
    meros = f.read()
    f.close()
  return meros

In [7]:
customer_tb, hotel_tb, reserve_tb = load_hotel_reserve()

print(reserve_tb)

     reserve_id hotel_id customer_id     reserve_datetime checkin_date  \
0            r1     h_75         c_1  2016-03-06 13:09:42   2016-03-26
1            r2    h_219         c_1  2016-07-16 23:39:55   2016-07-20
2            r3    h_179         c_1  2016-09-24 10:03:17   2016-10-19
3            r4    h_214         c_1  2017-03-08 03:20:10   2017-03-29
4            r5     h_16         c_1  2017-09-05 19:50:37   2017-09-22
...         ...      ...         ...                  ...          ...
4025      r4026    h_129       c_999  2017-06-27 23:00:02   2017-07-10
4026      r4027     h_97       c_999  2017-09-29 05:24:57   2017-10-09
4027      r4028     h_27       c_999  2018-03-14 05:01:45   2018-04-02
4028      r4029     h_48      c_1000  2016-04-16 15:20:17   2016-05-10
4029      r4030    h_117      c_1000  2016-06-06 08:16:51   2016-07-06

     checkin_time checkout_date  people_num  total_price
0        10:00:00    2016-03-29           4        97200
1        11:30:00    2016-07-21           2        20600
2        09:00:00    2016-10-22           2        33600
3        11:00:00    2017-03-30           4       194400
4        10:30:00    2017-09-23           3        68100
...           ...           ...         ...          ...
4025     09:30:00    2017-07-11           2        16000
4026     10:30:00    2017-10-10           2        41800
4027     11:30:00    2018-04-04           2        74800
4028     09:30:00    2016-05-13           4       540000
4029     09:00:00    2016-07-09           1        44100

[4030 rows x 9 columns]

In [8]:
reserve_tb[['reserve_id', 'hotel_id']]

     reserve_id hotel_id
0            r1     h_75
1            r2    h_219
2            r3    h_179
3            r4    h_214
4            r5     h_16
...         ...      ...
4025      r4026    h_129
4026      r4027     h_97
4027      r4028     h_27
4028      r4029     h_48
4029      r4030    h_117

[4030 rows x 2 columns]

In [12]:
reserve_tb.loc[:, ['reserve_id', 'hotel_id', 'customer_id', 'reserve_datetime', 'checkin_date', 'checkin_time', 'checkout_date']]

,reserve_id,hotel_id,customer_id,reserve_datetime,checkin_date,checkin_time,checkout_date
0,r1,h_75,c_1,2016-03-06 13:09:42,2016-03-26,10:00:00,2016-03-29
1,r2,h_219,c_1,2016-07-16 23:39:55,2016-07-20,11:30:00,2016-07-21
2,r3,h_179,c_1,2016-09-24 10:03:17,2016-10-19,09:00:00,2016-10-22
3,r4,h_214,c_1,2017-03-08 03:20:10,2017-03-29,11:00:00,2017-03-30
4,r5,h_16,c_1,2017-09-05 19:50:37,2017-09-22,10:30:00,2017-09-23
...,...,...,...,...,...,...,...
4025,r4026,h_129,c_999,2017-06-27 23:00:02,2017-07-10,09:30:00,2017-07-11
4026,r4027,h_97,c_999,2017-09-29 05:24:57,2017-10-09,10:30:00,2017-10-10
4027,r4028,h_27,c_999,2018-03-14 05:01:45,2018-04-02,11:30:00,2018-04-04
4028,r4029,h_48,c_1000,2016-04-16 15:20:17,2016-05-10,09:30:00,2016-05-13
4029,r4030,h_117,c_1000,2016-06-06 08:16:51,2016-07-06,09:00:00,2016-07-09

In [13]:
reserve_tb.drop(['people_num', 'total_price'], axis=1, inplace=True)

In [15]:
reserve_tb[(reserve_tb['checkout_date'] >= '2016-10-13') & (reserve_tb['checkout_date'] <= '2016-10-14')]

,reserve_id,hotel_id,customer_id,reserve_datetime,checkin_date,checkin_time,checkout_date
284,r285,h_121,c_67,2016-09-27 06:13:19,2016-10-12,12:00:00,2016-10-14
513,r514,h_74,c_120,2016-10-06 03:12:04,2016-10-11,12:30:00,2016-10-14
1065,r1066,h_205,c_261,2016-09-14 02:57:59,2016-10-11,10:00:00,2016-10-14
1480,r1481,h_116,c_364,2016-09-17 17:45:39,2016-10-11,11:30:00,2016-10-13
1546,r1547,h_149,c_377,2016-09-27 08:19:24,2016-10-10,11:00:00,2016-10-13
1709,r1710,h_59,c_422,2016-09-19 04:17:25,2016-10-10,12:00:00,2016-10-13
1932,r1933,h_113,c_477,2016-09-24 09:04:26,2016-10-12,11:30:00,2016-10-13
2058,r2059,h_9,c_517,2016-09-19 15:32:35,2016-10-11,12:30:00,2016-10-13
2115,r2116,h_77,c_527,2016-10-05 00:44:09,2016-10-11,09:00:00,2016-10-13
2170,r2171,h_177,c_540,2016-09-28 01:21:26,2016-10-11,10:00:00,2016-10-13
2203,r2204,h_82,c_549,2016-09-27 01:47:57,2016-10-10,12:00:00,2016-10-13
2290,r2291,h_230,c_574,2016-10-09 04:34:14,2016-10-12,12:00:00,2016-10-13
2523,r2524,h_203,c_631,2016-09-14 10:45:15,2016-10-12,10:30:00,2016-10-14
2555,r2556,h_193,c_639,2016-09-11 17:36:25,2016-10-11,10:30:00,2016-10-14
2734,r2735,h_178,c_690,2016-10-11 14:06:11,2016-10-11,09:00:00,2016-10-14
3010,r3011,h_156,c_761,2016-10-09 08:22:07,2016-10-11,11:30:00,2016-10-14
3136,r3137,h_218,c_792,2016-09-20 02:15:43,2016-10-10,10:30:00,2016-10-13
3327,r3328,h_23,c_833,2016-09-28 08:22:57,2016-10-13,09:00:00,2016-10-14
3605,r3606,h_147,c_900,2016-09-28 19:13:15,2016-10-10,12:00:00,2016-10-13
3770,r3771,h_93,c_939,2016-09-27 05:50:26,2016-10-10,12:30:00,2016-10-13

In [16]:
reserve_tb.loc[(reserve_tb['checkout_date'] >= '2016-10-13') & (reserve_tb['checkin_date'] <= '2016-10-14')]

,reserve_id,hotel_id,customer_id,reserve_datetime,checkin_date,checkin_time,checkout_date
47,r48,h_299,c_8,2016-10-05 08:53:39,2016-10-14,09:30:00,2016-10-16
284,r285,h_121,c_67,2016-09-27 06:13:19,2016-10-12,12:00:00,2016-10-14
327,r328,h_48,c_76,2016-10-11 15:51:25,2016-10-14,11:00:00,2016-10-16
513,r514,h_74,c_120,2016-10-06 03:12:04,2016-10-11,12:30:00,2016-10-14
959,r960,h_215,c_237,2016-09-19 05:51:20,2016-10-14,11:00:00,2016-10-16
1065,r1066,h_205,c_261,2016-09-14 02:57:59,2016-10-11,10:00:00,2016-10-14
1225,r1226,h_176,c_300,2016-09-19 22:11:19,2016-10-14,09:30:00,2016-10-16
1480,r1481,h_116,c_364,2016-09-17 17:45:39,2016-10-11,11:30:00,2016-10-13
1546,r1547,h_149,c_377,2016-09-27 08:19:24,2016-10-10,11:00:00,2016-10-13
1709,r1710,h_59,c_422,2016-09-19 04:17:25,2016-10-10,12:00:00,2016-10-13
1932,r1933,h_113,c_477,2016-09-24 09:04:26,2016-10-12,11:30:00,2016-10-13
1960,r1961,h_244,c_486,2016-09-19 03:05:50,2016-10-14,12:00:00,2016-10-15
2058,r2059,h_9,c_517,2016-09-19 15:32:35,2016-10-11,12:30:00,2016-10-13
2115,r2116,h_77,c_527,2016-10-05 00:44:09,2016-10-11,09:00:00,2016-10-13
2170,r2171,h_177,c_540,2016-09-28 01:21:26,2016-10-11,10:00:00,2016-10-13
2203,r2204,h_82,c_549,2016-09-27 01:47:57,2016-10-10,12:00:00,2016-10-13
2290,r2291,h_230,c_574,2016-10-09 04:34:14,2016-10-12,12:00:00,2016-10-13
2391,r2392,h_116,c_601,2016-10-13 04:45:54,2016-10-14,09:30:00,2016-10-15
2475,r2476,h_207,c_620,2016-09-16 00:59:40,2016-10-14,12:30:00,2016-10-17
2523,r2524,h_203,c_631,2016-09-14 10:45:15,2016-10-12,10:30:00,2016-10-14
2555,r2556,h_193,c_639,2016-09-11 17:36:25,2016-10-11,10:30:00,2016-10-14
2734,r2735,h_178,c_690,2016-10-11 14:06:11,2016-10-11,09:00:00,2016-10-14
3010,r3011,h_156,c_761,2016-10-09 08:22:07,2016-10-11,11:30:00,2016-10-14
3104,r3105,h_135,c_784,2016-10-10 18:01:19,2016-10-14,11:30:00,2016-10-16
3136,r3137,h_218,c_792,2016-09-20 02:15:43,2016-10-10,10:30:00,2016-10-13
3146,r3147,h_163,c_794,2016-10-02 07:35:16,2016-10-13,09:00:00,2016-10-16
3327,r3328,h_23,c_833,2016-09-28 08:22:57,2016-10-13,09:00:00,2016-10-14
3380,r3381,h_110,c_844,2016-09-17 17:44:02,2016-10-13,12:30:00,2016-10-15
3399,r3400,h_20,c_848,2016-09-17 12:18:15,2016-10-14,11:00:00,2016-10-15
3443,r3444,h_14,c_859,2016-10-03 17:26:00,2016-10-13,12:30:00,2016-10-15
3460,r3461,h_105,c_863,2016-09-22 14:42:06,2016-10-14,11:00:00,2016-10-16
3605,r3606,h_147,c_900,2016-09-28 19:13:15,2016-10-10,12:00:00,2016-10-13
3693,r3694,h_270,c_919,2016-09-27 07:26:21,2016-10-14,09:00:00,2016-10-16
3770,r3771,h_93,c_939,2016-09-27 05:50:26,2016-10-10,12:30:00,2016-10-13

In [17]:
reserve_tb.query('"2016-10-13" <= checkout_date <= "2016-10-14"')

,reserve_id,hotel_id,customer_id,reserve_datetime,checkin_date,checkin_time,checkout_date
284,r285,h_121,c_67,2016-09-27 06:13:19,2016-10-12,12:00:00,2016-10-14
513,r514,h_74,c_120,2016-10-06 03:12:04,2016-10-11,12:30:00,2016-10-14
1065,r1066,h_205,c_261,2016-09-14 02:57:59,2016-10-11,10:00:00,2016-10-14
1480,r1481,h_116,c_364,2016-09-17 17:45:39,2016-10-11,11:30:00,2016-10-13
1546,r1547,h_149,c_377,2016-09-27 08:19:24,2016-10-10,11:00:00,2016-10-13
1709,r1710,h_59,c_422,2016-09-19 04:17:25,2016-10-10,12:00:00,2016-10-13
1932,r1933,h_113,c_477,2016-09-24 09:04:26,2016-10-12,11:30:00,2016-10-13
2058,r2059,h_9,c_517,2016-09-19 15:32:35,2016-10-11,12:30:00,2016-10-13
2115,r2116,h_77,c_527,2016-10-05 00:44:09,2016-10-11,09:00:00,2016-10-13
2170,r2171,h_177,c_540,2016-09-28 01:21:26,2016-10-11,10:00:00,2016-10-13
2203,r2204,h_82,c_549,2016-09-27 01:47:57,2016-10-10,12:00:00,2016-10-13
2290,r2291,h_230,c_574,2016-10-09 04:34:14,2016-10-12,12:00:00,2016-10-13
2523,r2524,h_203,c_631,2016-09-14 10:45:15,2016-10-12,10:30:00,2016-10-14
2555,r2556,h_193,c_639,2016-09-11 17:36:25,2016-10-11,10:30:00,2016-10-14
2734,r2735,h_178,c_690,2016-10-11 14:06:11,2016-10-11,09:00:00,2016-10-14
3010,r3011,h_156,c_761,2016-10-09 08:22:07,2016-10-11,11:30:00,2016-10-14
3136,r3137,h_218,c_792,2016-09-20 02:15:43,2016-10-10,10:30:00,2016-10-13
3327,r3328,h_23,c_833,2016-09-28 08:22:57,2016-10-13,09:00:00,2016-10-14
3605,r3606,h_147,c_900,2016-09-28 19:13:15,2016-10-10,12:00:00,2016-10-13
3770,r3771,h_93,c_939,2016-09-27 05:50:26,2016-10-10,12:30:00,2016-10-13

In [14]:
reserve_tb.sample(frac=0.5)

,reserve_id,hotel_id,customer_id,reserve_datetime,checkin_date,checkin_time,checkout_date
630,r631,h_270,c_152,2016-12-14 12:23:57,2016-12-31,12:30:00,2017-01-02
1269,r1270,h_127,c_310,2016-06-12 22:58:37,2016-07-05,11:00:00,2016-07-07
2669,r2670,h_68,c_672,2017-05-07 13:17:34,2017-05-21,09:30:00,2017-05-24
1174,r1175,h_273,c_285,2017-12-03 15:14:45,2017-12-30,10:00:00,2018-01-02
2672,r2673,h_92,c_673,2016-03-16 14:45:17,2016-04-08,10:00:00,2016-04-11
...,...,...,...,...,...,...,...
3866,r3867,h_171,c_961,2017-10-03 00:13:55,2017-10-20,11:30:00,2017-10-22
471,r472,h_238,c_108,2017-08-18 16:12:20,2017-09-17,10:30:00,2017-09-18
2838,r2839,h_231,c_715,2016-04-06 02:51:01,2016-04-08,09:00:00,2016-04-10
1788,r1789,h_30,c_443,2016-12-29 07:47:13,2017-01-02,11:30:00,2017-01-04
3131,r3132,h_257,c_790,2017-02-25 17:50:02,2017-03-14,09:00:00,2017-03-15

In [18]:
target = pd.Series(reserve_tb['customer_id'].unique()).sample(frac=0.5)

In [19]:
reserve_tb[reserve_tb['customer_id'].isin(target)]

,reserve_id,hotel_id,customer_id,reserve_datetime,checkin_date,checkin_time,checkout_date
16,r17,h_115,c_3,2016-05-10 12:20:32,2016-05-17,10:00:00,2016-05-19
17,r18,h_132,c_3,2016-10-22 02:18:48,2016-11-12,12:00:00,2016-11-13
18,r19,h_23,c_3,2017-01-11 22:54:09,2017-02-08,10:00:00,2017-02-10
19,r20,h_292,c_3,2017-02-23 07:10:30,2017-03-03,11:00:00,2017-03-04
20,r21,h_153,c_3,2017-04-06 18:12:10,2017-04-16,09:00:00,2017-04-19
...,...,...,...,...,...,...,...
4019,r4020,h_243,c_996,2018-04-22 20:41:29,2018-05-21,12:00:00,2018-05-22
4020,r4021,h_159,c_997,2016-01-08 20:30:10,2016-01-09,12:00:00,2016-01-11
4021,r4022,h_172,c_997,2016-05-13 09:08:55,2016-06-06,09:30:00,2016-06-08
4028,r4029,h_48,c_1000,2016-04-16 15:20:17,2016-05-10,09:30:00,2016-05-13
4029,r4030,h_117,c_1000,2016-06-06 08:16:51,2016-07-06,09:00:00,2016-07-09